const KRAKEN_API_CENTER_HOST = 'https://docs.kraken.com'
module.exports.KRAKEN_API_CENTER_HOST = KRAKEN_API_CENTER_HOST

const KRAKEN_API_CENTER_URI = `${KRAKEN_API_CENTER_HOST}/api`
module.exports.KRAKEN_API_CENTER_URI = KRAKEN_API_CENTER_URI
